### ISSUE TITLE
Bad nlog dependency in nuget package.

### ISSUE THREAD

**Issue by jeresis** [csnemes/tracer#39]
If I have NLog 4.3.8 installed (the current minimum required version) and execute the following code I get a missing method exception.

```
var ex = new ArgumentNullException(nameof(args));
var str = "foo";
Tracer.NLog.Log.Error(ex, str);
```

If I upgrade to NLog 4.4.1 the exception goes away.

The exception:
```
Method not found: 'Void NLog.ILogger.Error(System.Exception, System.String)'.
   at Tracer.NLog.Adapters.LoggerAdapter.LogError(String methodInfo, Exception exception, String message)
   at ConsoleApplication2.Program.Main(String[] args) in c:\users\documents\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.cs:line 14
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by csnemes** [comment]
Thanks for spotting this. I've updated the dependency in the package.
