### ISSUE TITLE
Combination of ctor and parameters in TraceOn causes exception

### ISSUE THREAD

**Issue by ndrwrbgs** [csnemes/tracer#97]
e.g. `[TraceOn(TraceTarget.Private, IncludeArguments = true, IncludeReturnValue = true)]`

```stack

TargetSite:
Void ExecuteWeavers()
Specified cast is not valid.
Type:
System.InvalidCastException
StackTrace:
   at Tracer.Fody.Filters.TraceAttributeHelper.GetTargetVisibilityFromAttribute(CustomAttribute attribute) in c:\Work\tracer\Tracer.Fody\Filters\TraceAttributeHelper.cs:line 118
   at Tracer.Fody.Filters.TraceAttributeHelper.GetNearestTraceAttributeWalkingUpTheTypeNestingChain(TypeDefinition type) in c:\Work\tracer\Tracer.Fody\Filters\TraceAttributeHelper.cs:line 104
   at Tracer.Fody.Filters.TraceAttributeHelper.GetTraceAttributeInfoForType(TypeDefinition type) in c:\Work\tracer\Tracer.Fody\Filters\TraceAttributeHelper.cs:line 83
   at Tracer.Fody.Filters.TraceAttributeHelper.ShouldTraceBasedOnClassLevelInfo(MethodDefinition definition) in c:\Work\tracer\Tracer.Fody\Filters\TraceAttributeHelper.cs:line 62
   at Tracer.Fody.Filters.DefaultFilter.DefaultFilter.ShouldAddTrace(MethodDefinition definition) in c:\Work\tracer\Tracer.Fody\Filters\DefaultFilter\DefaultFilter.cs:line 46
   at Tracer.Fody.Weavers.TypeWeaver.Execute() in c:\Work\tracer\Tracer.Fody\Weavers\TypeWeaver.cs:line 65
   at Tracer.Fody.Weavers.ModuleLevelWeaver.InternalExecute() in c:\Work\tracer\Tracer.Fody\Weavers\ModuleLevelWeaver.cs:line 70
   at Tracer.Fody.Weavers.ModuleLevelWeaver.Execute(TraceLoggingConfiguration configuration, ModuleDefinition moduleDefinition) in c:\Work\tracer\Tracer.Fody\Weavers\ModuleLevelWeaver.cs:line 56
   at Tracer.Fody.ModuleWeaver.Execute() in c:\Work\tracer\Tracer.Fody\ModuleWeaver.cs:line 35
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 182

```

**Comment by ndrwrbgs** [comment]
[non-blocking, as from the code I could see that I just need to use ALL properties]

**Comment by csnemes** [comment]
fixed in the new version

**Comment by ndrwrbgs** [comment]
Thanks again!
